import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito, Bebas_Neue } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// Configure Nunito (Google Font)
const nunito = Nunito({
  subsets: ['latin'], // Adjust subsets as needed (e.g., 'latin-ext' for extended Latin)
  display: 'swap', // Prevents layout shift
  variable: '--font-nunito', // CSS variable for Tailwind
});

// Configure Bebas Neue (Google Font)
const bebas = Bebas_Neue({
  subsets: ['latin'],
  weight: '400', // Bebas Neue has only one weight
  display: 'swap',
  variable: '--font-bebas',
});

// Configure mono font (assuming a system font or custom font)
// Option 1: System monospace font
const mono = {
  variable: '--font-mono',
  className: 'font-mono', // Directly use system monospace
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${bebas.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
