name: PR Preview

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: |
          export BASE_PATH="/pr-preview/pr-${{ github.event.pull_request.number }}"
          echo "BASE_PATH=$BASE_PATH" >> $GITHUB_ENV
          npm run build

      - name: Create .nojekyll file
        run: touch out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          destination_dir: pr-preview/pr-${{ github.event.pull_request.number }}
          publish_branch: gh-pages
          force_orphan: false

      - name: Comment PR with Preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview-url
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            🚀 Preview deployed: https://decleanup-network.github.io/pr-preview/pr-${{ github.event.pull_request.number }}
